# This is the configuration for Azure pipelines. It currently runs a build of
# the web client SDK and publishes the wwtsdk.js file as a build artifact.

trigger:
  branches:
    include:
    - '*'

pr:
  branches:
    include:
    - '*'

jobs:
- job: BuildSDK
  pool:
    vmImage: vs2015-win2012r2

  steps:

  - task: MSBuild@1
    displayName: Building web client
    inputs:
      solution: 'Html5Sdk.sln'
      msbuildVersion: '14.0'
      msbuildArchitecture: 'x64'
      clean: true

  - task: NodeTool@0
    displayName: Setting up node

  - script: npm install
    workingDirectory: 'webclient'
    displayName: Install NPM dependencies

  - script: npm install -g grunt-cli
    workingDirectory: 'webclient'
    displayName: Installing grunt

  - task: Grunt@0
    displayName: Running grunt
    inputs:
      gruntFile: 'webclient\Gruntfile.js'
      targets: sdk
      workingDirectory: 'webclient'

  - task: CopyFiles@2
    displayName: Copying SDK file to staging directory
    inputs:
      sourceFolder: 'webclient\sdk'
      contents: 'wwtsdk.js'
      targetFolder: $(Build.ArtifactStagingDirectory)
      cleanTargetFolder: true

  - task: PublishPipelineArtifact@0
    displayName: Publishing SDK artifact
    inputs:
      artifactName: wwtsdk.js
      targetPath: $(Build.ArtifactStagingDirectory)

  - script: npm install mocha chai mocha-headless-chrome --save-dev
    workingDirectory: tests
    displayName: Installing mocha testing framework

  - script: node_modules/.bin/mocha-headless-chrome -f tests.html -r xunit > test_results.xml
    workingDirectory: tests
    displayName: Running tests against JS SDK

  # NOTE: The file produced above is actually in JUnit format, not xUnit!
  - task: PublishTestResults@2
    condition: succeededOrFailed()
    inputs:
      testResultsFormat: 'JUnit'
      testResultsFiles: 'tests/test_results.xml'

